### ISSUE TITLE
Missing EditorWindow.GetRowsFromIDs() definition

### ISSUE THREAD

**Issue by Tyrannicus100BC** [Unity-Technologies/AssetBundles-Browser#1]
I'm using Unity 5.6.0b8 and AssetBundles-Browser git hash d0f494d9fe412636a1c146a0f56ea8854fbb26a9

EditorWindow doesn't have a definition for GetRowsFromIDs(). I have locally replaced it with GetRows().Where(a => ids.Contains(a.id)).

**Comment by paulb-unity** [comment]
Thanks for the report and suggested fix.  We'll get this updated ASAP.
