### ISSUE TITLE
"EndLayoutGroup: BeginLayoutGroup must be called first." on build

### ISSUE THREAD

**Issue by paweleck** [Unity-Technologies/AssetBundles-Browser#101]
I get error when I press Build button:

> EndLayoutGroup: BeginLayoutGroup must be called first.
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Error leads to line 260 in AssetBundleBuildTab.cs:
`EditorGUILayout.EndScrollView();`

Unity 2018.1.8f1

**Comment by ilirvg** [comment]
I am facing the same issue

**Comment by alffanclub** [comment]
Are you guys running directly from github, or are you running through package manager?  If github, are you running latest master? If package manager, which version are you on?
Thanks,
Bill

**Comment by kaznog** [comment]
Hi Bill,

Do not use package manager. With Github, you can see immediately what
changes have been made and it's easy to understand what updates I need. I
think that timing is good for updating. Whether it is necessary for me or
not, it is important. I think that it is good that an unnecessary process
is not added to the editor from such a thing, and it is simple and light.
Unity does not want to increase work as we want Unity to continue its
wonderful work.

Thanks,
Kazuya Noguchi

2018年8月6日(月) 22:45 Bill <notifications@github.com>:

**Comment by alffanclub** [comment]
Closing this as I need more information.  Please reopen if more info is available.
