### ISSUE TITLE
Add option for build AssetBundleBuild.addressableNames

### ISSUE THREAD

**Issue by wobes1** [Unity-Technologies/AssetBundles-Browser#109]
Good day.

Could you add a build options to change addressable names? 
https://docs.unity3d.com/ScriptReference/AssetBundleBuild-addressableNames.html

Thank you.

**Comment by alffanclub** [comment]
That would have large UI implications and be too significant of an overhaul for this tool.  If you need that sort of custom loading, I suggest you look into the addressable asset system which is supported as of 2018.2.+ 
https://forum.unity.com/forums/addressables.156/

**Comment by wobes1** [comment]
Thank you.
