### ISSUE TITLE
ShaderVariants?

### ISSUE THREAD

**Issue by cpxnet** [Unity-Technologies/AssetBundles-Browser#12]
I pack a shaderVariantCollection object and all relevent shaders into one assetbundle.
Is it possible to check which variants ware actually generated using assetBundleBrowser?

**Comment by alffanclub** [comment]
Hi @cpxnet, unfortunately, no we can't determine that. We are planning to add a feature that allows you to inspect what was put into bundles, but that won't go to the level of which variant is in a shaderVariantCollection. The data is just not exposed with those to be able to inspect them.
