### ISSUE TITLE
[New Feature]SBP support

### ISSUE THREAD

**Issue by Rootjhon** [Unity-Technologies/AssetBundles-Browser#134]
it's possiable support the new feature SBP ,which can sign the different bundle with different different compress model?  waitting for that. @alffanclub

**Comment by alffanclub** [comment]
for the tab where you view your bundle layout:
- SBP has two methods to build. building the same way the engine does (so no changes needed) or building bundle data passed in (so no changes that would make sense)
for the tab where you build:
- that build script is a sample intended to be modified/replaced/referenced.  If you would like to build with SBP (which you should, though you really should just jump to addressables, but imaginging you don't...), it's the same recommendation I have for anyone building any bundles, don't use the script in the browser, use that as a reference.

**Comment by Rootjhon** [comment]
maybe i will add it by myself.to support  "A" Bundle with LZMA ,"B" Bundle with LZ4  at the same time build with SBP.   doesn't recommend do with this way?
