### ISSUE TITLE
`Is auto included in bundle(s) due to parent(s)` does not refresh when creating new assets

### ISSUE THREAD

**Issue by plunntic** [Unity-Technologies/AssetBundles-Browser#15]
I have such file structure under `Assets`:

```
Content/
- Data/
- - Environment/
- - Settings/
```

There are some assets under both Environment and Settings (`ScriptableObject` instances in this case).

When i drag Data directory into AssetBundle window it properly create new bundle and includes all assets in that directory (also the directory itself).

Now when i add new asset under Settings directory it should be visible in the bundle created from Data directory, but it's not. Hitting refresh button inside AssetBundle window also does nothing in this case.

Restarting Unity - however - force the refresh properly and after restart all newly created assets are visible in the bundle created from Data directory.

**Comment by plunntic** [comment]
Here's an image showing AssetBundle-Browser window after hitting refresh button couple times.

As you can see Test55 asset should be visible in data bundle.

![unity-temp-01](https://cloud.githubusercontent.com/assets/22856697/26649962/2408f84a-4648-11e7-9baa-32a7acea7501.png)

**Comment by plunntic** [comment]
Ok, it looks like reselecting the bundle (in bundle list inside AssetBundles window) also cause things to refresh and after that it shows bundle content properly.

**Comment by alffanclub** [comment]
Thanks for your feedback plunntic. Unfortunately it's very difficult to monitor changes in your project outside the tool window. It is, however, something that I was planning to investigate further, so I'll leave this ticket open until I can either fix it, or fully convince myself it can't be fixed. I'll update once I know more. Thanks again for reaching out!

**Comment by plunntic** [comment]
After some more testing i can see that bundles are built correctly (even if they're display is out of sync) (at least when using `BuildPipeline`) so it's not a deal-breaker by any means. But AssetBundles window can be very useful for especially managing and visualising asset bundles and their correlations in medium / bigger projects. So in this case it would be cool if it could be fixed somehow.

Staying tuned for future updates on the topic!

**Comment by halleyxu** [comment]
wating for this case be fixed

**Comment by alffanclub** [comment]
Sorry I've let this sit so long. I investigated it a while ago, without a good way to fix it, then put it on the back-burner hoping something would come to me...  and then forgot about it :(
So I've dug back into it.  There is a callback I could use to monitor file changes, but it would significantly affect performance on any decently large game. This example case actually shows the issue well. The file  being added is "Test55", not only is it not marked for an asset bundle, but its parent ("Settings") is not either.  So what I'd have to do on every single file change is search up the file path to see if anywhere up the chain is in a bundle. Now, lets make it more complex, say Test55 was a material. It wasn't new, it was just moved from some random spot to "Data/Settings". Now I not only need to figure out that Test55 is now in a specific bundle, I have to look through all other bundles to figure out if they had Test55 as a dependency. That gets really expensive.

So I'm going to have to close this one. I don't love the fact that its here, but the workaround is so simple its not worth the performance and robustness hit to fix it.

**Workaround**: re-select the bundle.
