### ISSUE TITLE
So much null

### ISSUE THREAD

**Issue by Insanto** [Unity-Technologies/AssetBundles-Browser#23]
When opening the window I get a slew of null exceptions:

![capture_07032017_155321](https://user-images.githubusercontent.com/3212427/27795807-ca9623bc-6007-11e7-9bce-ec69ebaa577e.png)

**Comment by Insanto** [comment]
In the ABModelAssetinfo Getdependencies you return null on a folder, that isn't accounted for in the ABModelBundleInfo Gatherdependencies method's for loop.

Suggested alteration: 
```
    private void GatherDependencies(AssetInfo asset, string parentBundle = "")
    {
      if (parentBundle == string.Empty)
        parentBundle = asset.bundleName;

      var deps = asset.GetDependencies();
      if (deps == null)
        return;

      foreach (var ai in deps)
      {
        if (ai == asset || m_ConcreteAssets.Contains(ai) || m_DependentAssets.Contains(ai))
          continue;

        var bundleName = AssetBundleModel.Model.DataSource.GetImplicitAssetBundleName(ai.fullAssetName);
        if (string.IsNullOrEmpty(bundleName))
        {
          m_DependentAssets.Add(ai);
          m_TotalSize += ai.fileSize;
          if (Model.RegisterAsset(ai, parentBundle) > 1)
          {
            SetDuplicateWarning();
          }
        }
        else if (bundleName != m_Name.fullNativeName)
        {
          m_BundleDependencies.Add(bundleName);
        }
      }
    }
```

**Comment by kaznog** [comment]
When Model.CreateAsset is not AssetInfo,
Because m_DependentAssets.Last () will be null,
It gets NullReferenceException when trying to get fileSize.

If Model.CreateAsset may return null,
A null check is required.

**Comment by kaznog** [comment]
I can not confirm it because I never encountered a problem.
You may be able to solve the problem by making the following modifications.

ABModelBundleInfo.cs
```
353:                        AssetInfo addAssetInfo = Model.CreateAsset(assetName, folderAsset);
354:                        if (addAssetInfo != Null)
355:                        {
356:                            m_DependentAssets.Add(addAssetInfo);
357:                            m_TotalSize += m_DependentAssets.Last().FileSize;
358:                        }
```

**Comment by Insanto** [comment]
Oh, I already fixed it for myself but there was a LOT that wasn't foolproofed, not just one.

**Comment by kaznog** [comment]
I think that it is good to be able to fix it freely.

**Comment by kaznog** [comment]
I would be happy if you tell me the incomplete part.

**Comment by Insanto** [comment]
There were about 20+ things i had to change to make it work properly, I can zip it up and you can diff it yourself if you like.

**Comment by Insanto** [comment]
[AssetBundleBrowser.zip](https://github.com/Unity-Technologies/AssetBundles-Browser/files/1121926/AssetBundleBrowser.zip)

**Comment by alffanclub** [comment]
Thanks for letting us know you're having a problem @Insanto, and especially for providing a solution that solved it for you!  I'll work on integrating your fix and should have it up in the master branch soon.

**Comment by alffanclub** [comment]
@Insanto, the null checking is in master now.  If you run into any more null issues, please let me know.  Also, thanks @kaznog for chiming in with helpful ideas.

**Comment by Insanto** [comment]
To replicate set up a faulty asset bundle (scene, scripts and assets all marked for the bundle) that revealed a lot of things that needed fixing.

**Comment by alffanclub** [comment]
Thanks @Insanto. I'll work on creating some more fail states to catch these edge cases.  If you run into any more issues, please don't hesitate to open another ticket.
