### ISSUE TITLE
Build one Asset Bundle

### ISSUE THREAD

**Issue by Arugin** [Unity-Technologies/AssetBundles-Browser#26]
I have 10 Asset Bundles and change one resource in the one Asset Bundle which has no dependencies. Is any way to rebuild only one asset bundle, but not all 10? Do you plan to add this feature?

**Comment by kaznog** [comment]
After changing one bundle
1. Switch to the build tab.
2. Select a platform. Be careful with the output destination. If you are using AssetBundleManager, for example, AssetBundles / Android or AssetBundles / iOS would be good.
3. Please do the compression method same as last time.
4. There are several check boxes, please do not ClearFolder or ForceBuild.
5. Click the Build button.

Only the Manifest file and the modified AssetBundle file should be updated.

**Comment by kaznog** [comment]
It is safe to back up for confirmation of operation

**Comment by alffanclub** [comment]
Thanks @kaznog for replying. @Arugin those steps mentioned will work.  
- ClearFolder will wipe out old bundles before telling Unity to build (obviously requiring everything to rebuild)
- ForceBuild _off_ will tell Unity to attempt to do an incremental build.
- if none of the other settings changed (compression, etc.) and the only resource that changed was explicitly added to bundles, it should successfully do an incremental build.  If your resource touches other things, or has other resources dependent on it, the incremental build may rebuild more than just the one bundle.  

All in all, the build tab is intended to be a starting off point. It covers the basic build but many teams that require something more complex will need to write their own build code.  Thanks for trying out the tool!

**Comment by Arugin** [comment]
Thanks for response. There is only one problem: when Clear folders checkbox turned off and Copy to Streaming Assets turned on it fails with File Exists exception. I think, it should override files in this case.

**Comment by alffanclub** [comment]
Ah yes, I see the issue there. I will get a fix in soon. In the interim, you can just edit it yourself...  In AssetBundleBuildTab.cs, on line 381, there is "file.CopyTo(temppath, false)". Change that false to a true and it will overwrite. Like I said, I'll get that fix in soon, but wanted to give you the fix asap so you can proceed. Let me know how that turns out.

**Comment by Arugin** [comment]
Thanks a lot.
