### ISSUE TITLE
Bundle Data Source setting automatically resets to "Default(Built-in)" on starting play mode

### ISSUE THREAD

**Issue by mhama** [Unity-Technologies/AssetBundles-Browser#29]
I'm using AssetBundles-Browser with AssetBundleGraphTool, and therefore, I'm choosing  "AssetBundles(GraphTool)" for Bundle Data Source setting. But it automatically changes to "Default(Built-in)", when I start play mode on Unity Editor.

Environment: Unity 5.6.2p1 on Mac OS X (Sierra).

As I looking into the source code, the ABDataSource value is retained in the AssetBundleModel.Model as static variable, so it will automatically resets to null on starting play mode.

https://github.com/Unity-Technologies/AssetBundles-Browser/blob/master/UnityEngine.AssetBundles/Editor/AssetBundleBrowser/AssetBundleModel/ABModel.cs#L19

**Comment by alffanclub** [comment]
Thanks for pointing this out to us. Doesn't sound too hard to fix, so hopefully can have something out soon.

**Comment by alffanclub** [comment]
@mhama this should be fixed in master now.
