### ISSUE TITLE
Unable to overwrite AssetBundles

### ISSUE THREAD

**Issue by NoxMortem** [Unity-Technologies/AssetBundles-Browser#33]
[Exception] IOException: Could not create file "<path>\<bundle>.manifest" or "Assets/StreamingAssets\<bundle>.manifest". File already exists.
(wrapper remoting-invoke-with-check) System.IO.FileInfo:CopyTo(string,bool)
File.InternalCopy()    /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/File.cs:122

FileInfo.CopyTo()    /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/io/fileinfo.cs:316

AssetBundleBuildTab.DirectoryCopy()    Assets/Editor/AssetBundleBrowser/AssetBundleBuildTab.cs:381
379:   {
380:       string temppath = Path.Combine(destDirName, file.Name);
-->381:       file.CopyTo(temppath, false);
382:   }

AssetBundleBuildTab.ExecuteBuild()    Assets/Editor/AssetBundleBrowser/AssetBundleBuildTab.cs:362
361:       if(m_CopyToStreaming.state)
-->362:           DirectoryCopy(m_UserData.m_OutputPath, m_streamingPath);
363:   }

EditorApplication.Internal_CallDelayFunctions()    C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:118

It might be on purpose that the browser can't overwrite existing bundles - in this case comment and close the issue. However, I would really have expected it does, as a bundle with the same name, when rebuild for the same target platform is more or less an update of the same bundle.

**Comment by alffanclub** [comment]
@NoxMortem yeah, this is definitely an issue and it will be fixed in the next update.  I was simply not sending the correct parameter to the system method.

**Comment by alffanclub** [comment]
@NoxMortem this should be fixed in master now.
