### ISSUE TITLE
Corrupt AssetBundle Browser Database?

### ISSUE THREAD

**Issue by markvitapoly** [Unity-Technologies/AssetBundles-Browser#37]
I dragged in a folder with only scripts into the assetbundle browser from the project tab. After that, the assetbundle browser is empty and spams the following message:

Where is the assetbundle listview model saved? Can I delete it and start over? I can't seem to find it in the project folder. 

`NullReferenceException: Object reference not set to an instance of an object
UnityEngine.AssetBundles.AssetBundleModel.BundleDataInfo.RefreshDupeAssetWarning () (at Assets/Standard Assets/AssetBundleBrowser/UnityEngine.AssetBundles/Editor/AssetBundleBrowser/AssetBundleModel/ABModelBundleInfo.cs:473)
UnityEngine.AssetBundles.AssetBundleModel.BundleInfo.RefreshMessages () (at Assets/Standard Assets/AssetBundleBrowser/UnityEngine.AssetBundles/Editor/AssetBundleBrowser/AssetBundleModel/ABModelBundleInfo.cs:184)
UnityEngine.AssetBundles.AssetBundleModel.BundleDataInfo.Update () (at Assets/Standard Assets/AssetBundleBrowser/UnityEngine.AssetBundles/Editor/AssetBundleBrowser/AssetBundleModel/ABModelBundleInfo.cs:435)
UnityEngine.AssetBundles.AssetBundleModel.BundleFolderInfo.Update () (at Assets/Standard Assets/AssetBundleBrowser/UnityEngine.AssetBundles/Editor/AssetBundleBrowser/AssetBundleModel/ABModelBundleInfo.cs:789)
UnityEngine.AssetBundles.AssetBundleModel.Model.Update () (at Assets/Standard Assets/AssetBundleBrowser/UnityEngine.AssetBundles/Editor/AssetBundleBrowser/AssetBundleModel/ABModel.cs:55)
UnityEngine.AssetBundles.AssetBundleManageTab.Update () (at Assets/Standard Assets/AssetBundleBrowser/UnityEngine.AssetBundles/Editor/AssetBundleBrowser/AssetBundleManageTab.cs:78)
UnityEngine.AssetBundles.AssetBundleBrowserMain.Update () (at Assets/Standard Assets/AssetBundleBrowser/UnityEngine.AssetBundles/Editor/AssetBundleBrowser/AssetBundleBrowserMain.cs:101)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:285)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:278)
UnityEditor.HostView.SendUpdate () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:354)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:127)
`

EDIT:
Looks like that information is stored in the .meta files. I removed the affected meta files and the assetbundle browser was able to load correctly.

**Comment by alffanclub** [comment]
@markvitapoly Thanks for letting me know about this. It's definitely a bug. The code handles folders with stuff, and folders without stuff. But it doesn't really handle folders with stuff-that-doesn't-count-as-stuff. So I'll get to fixing that. 
In the interim, the way to fix most issues in the browser (if you can figure out what asset/folder/stuff is causing the problem) is to select the problem thing and change it's bundle to "none" in it's inspector. 
 In this case you'd find the folder in your Project view, and then at the bottom of the folders Inspector, you'd see which bundle it was in.  This is the same way you'd have to do all bundle editing if you didn't have the browser.

**Comment by isurfraz** [comment]
what meta data do we need to delete?!

**Comment by alffanclub** [comment]
You're right, this should have been fixed a while ago. It slipped through the cracks. It's now in Master, and will be updated in package manager next time we do a release.
