### ISSUE TITLE
Build Tab Settings Keeps Resetting

### ISSUE THREAD

**Issue by markvitapoly** [Unity-Technologies/AssetBundles-Browser#43]
The AssetBundles Browser Window, Build Tab settings are not saved. 

The Build Target and the Output Path and all the advanced settings resets after closing the window and opening it again. Is this a bug or is saving not yet implemented?

**Comment by alffanclub** [comment]
That's definitely a bug, and on my machine I can't repro it. Got a few questions to help me:
1. Are you running on mac or windows? 
2. Does anything from the build window get saved? Such as "Force Rebuild" or "Strict Mode" check boxes.
3. Does it clear when you close and reopen the window _without_ closing Unity, or do you need to close the Unity editor as well?
4. Can you check that after closing the window, you have this file: /Library/AssetBundleBrowserBuild.dat? All the options are saved/restored through that file.

Thanks for submitting this. Hopefully we can get to the bottom of it.
-Bill

**Comment by alffanclub** [comment]
Closing this out as I havne't gotten any new information.
