### ISSUE TITLE
Unable to rename asset bundles on Mac OSX

### ISSUE THREAD

**Issue by rachelggarza** [Unity-Technologies/AssetBundles-Browser#53]
New bundles aren't created in naming mode (it auto-assigns it "newbundle..."), and right-click Rename also doesn't seem to allow the user to rename a bundle.
**OS, Editor Version:** Mac OSX 10.12.6, 2017.2.0b5
**Prerequisite(s):** a test project with the Asset Bundle browser source code in it, some test assets
**Steps to Reproduce:**
1. Right-click somewhere in the Asset Bundle Browser.
2. Select Add new bundle.
3. Right click your new bundle and select Rename.

**Comment by alffanclub** [comment]
appears to have been a fluke only on .0b5 and is gone now.
