### ISSUE TITLE
Configure View: "null texture passed to GUI.DrawTexture" Warnings

### ISSUE THREAD

**Issue by cfoulston** [Unity-Technologies/AssetBundles-Browser#56]
Seems to only happen with certain Textures. No image icons are showing and the console is spammed with warnings:

"null texture passed to GUI.DrawTexture"

Caused by:

AssetListTree -> CellGUI -> GUI.DrawTexture(iconRect, item.icon, ScaleMode.ScaleToFit);

simple null check does the job:

if (item.icon != null) GUI.DrawTexture(iconRect, item.icon, ScaleMode.ScaleToFit);

**Comment by alffanclub** [comment]
Good catch. Thanks for letting me know, I'll definitely get this in.

**Comment by alffanclub** [comment]
@cfoulston fixed and in master. thanks again!
