### ISSUE TITLE
Is batchmode api support in plan?

### ISSUE THREAD

**Issue by zenjugit** [Unity-Technologies/AssetBundles-Browser#65]
or how could i itegrate AssetBundles-Browser to my automate tools?

**Comment by alffanclub** [comment]
@zenjugit  Are you asking how to get the output from your automation tools into the bundle browser?  If so, you can look at the code in AssetBundleDataSource for how the browser consumes data, and you can look at https://bitbucket.org/Unity-Technologies/assetbundlegraphtool to see an example of a tool that is setup to be integrated. If you're asking something else, please give me some more details.
Thanks for reaching out.
-Bill

**Comment by alffanclub** [comment]
One more thing... I just somewhat glossed over the word "batchmode" in my first read.  Not really sure how that would be relevant as the bundle browser is purely a visual browser of the bundle data. Unless you want to use it to build your bundles from batch mode.  If it's the latter, then you should be able to edit the browser relatively simply to expose that.  If you're not asking about that, then my original answer probably still stands.

**Comment by zenjugit** [comment]
thanks, the second answer is exactly what i want.
AssetBundles-Browser is a very good tool , and i want to add it to my project.
Now i run ci build and auto test daily, without open unity nor open some uiwindows, 
so if there is an batchmode api to build assetbundle would be very happy for me.

**Comment by alffanclub** [comment]
Ah, that makes sense. Hopefully it's straightforward for you to customize that build script to work in batchmode to your needs.  We don't have plans right now to make this command line friendly because most people that get to the point of building from the command line are far enough along that they'll likely need to customize the build script anyway.  If you see a simple way to expose things that you think would be general purpose, feel free to let me know here, or create a PR into the project!  
Thanks again for reaching out.

**Comment by 0kk470** [comment]
For anyone interested, I find out if you already add bundle folders in the AssetBundleBrowser window , you can just write a wrapper class and call the build method in batchmode.

``` Csharp   
 public static class BuildCommand
    {
        public static void BuildAssetBundles()
        {
            BuildPipeline.BuildAssetBundles("E:/buildtest", BuildAssetBundleOptions.None, BuildTarget.StandaloneWindows);
        }
    }
```
Here is my batch file on jenkins.
``` bat
echo  Building AssetBundles

set Unity="C:\Program Files\Unity\Editor\Unity.exe" 

set ProjectPath=E:\MyGame

set logFilePath = E:/buildtest/buildlog.log

%Unity% -quit -batchmode -projectPath "%ProjectPath%" -logfile "%logFilePath%" -executeMethod BuildCommand.BuildAssetBundles

echo   Done

PAUSE
```
