### ISSUE TITLE
The project *projectname*.Editor cannot be added to the solution 

### ISSUE THREAD

**Issue by arvz** [Unity-Technologies/AssetBundles-Browser#66]
Imported the AssetBundles-Browser-Master folder into my project and got the error message in Visual Studio 2017:

![image](https://user-images.githubusercontent.com/3252230/35024071-b3a97a52-fb91-11e7-80db-1ab7e6561bb5.png)

_The project 'projectnamehere.Editor' cannot be added to the solution because a project with the same project filename already exists in the solution._

This error comes up, if you press OK it comes up a second time. After that, VS2017 takes you to your code and everything appears fine, except autocompleting Unity stuff no longer works in any Editor scripts. 

If I delete the folder and restart VS2017 everything is fine again

**Comment by alffanclub** [comment]
@arvz what version of Unity are you using? We added .asmdef files to the project, but I believe there may be some versions of Unity that have issues creating the VS projects when those are present. As a workaround for now, you can probably delete "Editor/com.unity.assetbundlebrowser.Editor.asmdef" and "Tests/Editor/com.unity.assetbundlebrowser.EditorTests.asmdef".
Please let me know which version you're running, and if deleting the asmdef's fixed it. 

Thanks for letting us know about this issue,
Bill

**Comment by arvz** [comment]
@alffanclub I'm using Unity 2017.3.0f3, If I delete the 2 .asmdef files, this happens when I open the browser:

![image](https://user-images.githubusercontent.com/3252230/35071307-5fd2a554-fc34-11e7-8724-936b6dc5d1bc.png)

https://pastebin.com/rJniLSDy

**Comment by alffanclub** [comment]
Thanks for all the details. Yeah, asmdef files work in mysterious ways that I also don't fully understand :) 

I'll test a few different versions of 17.3.  If it's isolated to 0f3, we may be ok, but if it's broken for all of 17.3, I may need to diverge the browser development. Hmm.

Well, thanks again. I'm glad you've got a good workaround, and hopefully I can land on a more permanent fix that doesn't cause people too much grief.

**Comment by arvz** [comment]
@alffanclub Just FYI I've figured out what the actual problem was - it was just that I was running a slightly older version of Visual Studio which doesn't support asmdefs. Once I updated Visual Studio to the latest version everything is fine. Confirmed this with someone else in the forums mentioning the same thing

**Comment by GuismoW** [comment]
Hello, I have approximately the same error when opening a CSharp file from Unity into VS
![image](https://user-images.githubusercontent.com/7024271/40578854-f66bf334-611b-11e8-8212-e43637c240b9.png)

The Unity version is 2018.2 Beta 5
I don't know what to do, IntelliSense doesn't work as it should

**Comment by GuismoW** [comment]
HI. I reinstalled completely updated Visual Studio, and it worked

**Comment by strebern** [comment]
Hey ! I had the same issue and updated my Visual Studio Community to the newest version and it worked.

**Comment by SyllabusGames** [comment]
I was able to fix this error message on my project by opening ProjectName.sln in notepad and deleting the duplicate entries at the top.

**Comment by Akeronz** [comment]
Unity 2018.2 had very similar issue right after upgrading from 2018.1

Solved: Updated Visual Studio 2017 community to V.15.7.6 (previously had V.15.3.x). Thanks for the tips guys!

That's why I don't like upgrades.... (aren't those to have fewer bugs, not more??)

**Comment by AFIDclan** [comment]
None of these worked. After updating VS to the latest version I had to delete all the .csproj files and the .sln from the project, then it rebuilt and worked.

**Comment by kalibcrone** [comment]
I opened the project .SLN file in notepad like @SyllabusGames suggested and I noticed a lot of duplicate lines at the top that looked like this: 

```
project("AAA"= "projectName","","")
EndProject
project("AAA"= "projectName","","")
EndProject
project("AAA"= "projectName","","")
EndProject
project("AAA"= "projectName.Plugins","","")
EndProject
project("AAA"= "projectName.Plugins","","")
EndProject
project("AAA"= "projectName.Plugins","","")
EndProject
project("AAA"= "projectName.Editor","","")
EndProject
project("AAA"= "projectName.Editor","","")
EndProject
project("AAA"= "projectName.Editor","","")
EndProject
```

But then I removed all duplicates and it looked something like this, and it worked:
```
project("AAA"= "projectName","","")
EndProject
project("AAA"= "projectName.Plugins","","")
EndProject
project("AAA"= "projectName.Editor","","")
EndProject
```

I honestly do not know what caused the duplicates or even what these lines do, so if anyone has some more insight, that'd be awesome!
