### ISSUE TITLE
Platform transition

### ISSUE THREAD

**Issue by kolodi** [Unity-Technologies/AssetBundles-Browser#67]
When I start to build bundles for different platform (For example: I am most of the time on Android, and often should build bundles for iOS) editor initiates platform changing and optimization for every single asset in the entire project. This takes a lot of time in big projects. I know I can use cache server, but it add overhead for the editor and it still seems waste of resources to convert (download from cache) all the assets.  Is there any chance to trigger "platform changing" procedure only for CHANGED assets that are actually INCLUDED in any asset bundle?

**Comment by alffanclub** [comment]
Hi @kolodi, unfortunately the asset importing has nothing to do with the build time behavior.  As of now, all assets are needed when the project is open, even if they aren't actually used. I believe another team is working on a fix to this, but I am not aware of their timeline.
Thanks for reaching out,
Bill
