### ISSUE TITLE
System.IO.IOException: Sharing violation on path when trying to copy to StreamingAssets

### ISSUE THREAD

**Issue by RDeluxe** [Unity-Technologies/AssetBundles-Browser#69]
I'm trying to fix this error, without luck for now. I'm getting Sharing violations on all the built files, and I can't find which process is locking them.

**Comment by alffanclub** [comment]
Thanks for letting me know about this.  I can think of a few things that might cause this, though I don't believe I've seen it.  I'll try out a few scenarios to see what I can come up with.
To help me repro, are you running on Mac or Windows?
Thanks,
Bill

**Comment by RDeluxe** [comment]
Hi,

I'm on Windows, and I fixed the bug. A `Replace("\\", "/")` is missing in the `AssetBuildTab.DirectoryCopy` method.

I've been refactoring the code to use some C#6 features and to better respect .NET naming conventions, I don't know if you might be interested in supporting such a refactoring. In any case, I will probably push it on a forked version

**Comment by alffanclub** [comment]
Thanks for working out the fix.  I'd be happy to look at your changes.  The reason it's in a public repo is to get this kind of feedback.  If you do have a fork you push up somewhere, please share a link here so I can see what kinds of things you're doing.

**Comment by dfineberg** [comment]
I'm also getting this on Windows 10.
Here's the stack trace:

IOException: Sharing violation on path AssetBundles/StandaloneWindows\StandaloneWindows" or "AssetBundles\StandaloneWindows\StandaloneWindows
System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
AssetBundleBrowser.AssetBundleBuildTab.DirectoryCopy (System.String sourceDirName, System.String destDirName) (at Assets/AssetBundles-Browser/Editor/AssetBundleBuildTab.cs:387)
AssetBundleBrowser.AssetBundleBuildTab.ExecuteBuild () (at Assets/AssetBundles-Browser/Editor/AssetBundleBuildTab.cs:365)
UnityEditor.EditorApplication.Internal_CallDelayFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:136)

**Comment by Arugin** [comment]
Reproduced in the 1.5.0

**Comment by Seromu** [comment]
v1.6.0 same.

**Comment by ishtilkind** [comment]
The same problem with WebGL build on Unity 2018.2.0b8

**Comment by horeaper** [comment]
Only happens when "Copy to StreamingAssets" is checked, and no assets are copied.
Fixed by changing the output path from the default "AssetBundles/StandaloneWindows64" to "AssetBundles\StandaloneWindows64"
I'm pretty sure this problem only happens on windows platform...

**Comment by NoxMortem** [comment]
@BrettKercher Issue still exists in Unity 2018.2.0f2 on package manager version 1.9.11
```
[Exception] IOException: Sharing violation on path AssetBundles/StandaloneWindows\rednerpult" or 
"AssetBundles\StandaloneWindows\rednerpult
File.Copy()    <f826c2584fc94ec19a48a6576640bdc5>:0

AssetBundleBuildTab.DirectoryCopy()    C:/Users/Kevin Streicher/AppData/Local/Unity/cache/packages/packages.unity.com/com.unity.assetbundlebrowser@1.6.0/Editor/AssetBundleBuildTab.cs:386
384:               Path.GetFileName(filePath));
-->386:           File.Copy(filePath, newFilePath, true);
387:       }
388:   }

AssetBundleBuildTab.ExecuteBuild()    C:/Users/Kevin Streicher/AppData/Local/Unity/cache/packages/packages.unity.com/com.unity.assetbundlebrowser@1.6.0/Editor/AssetBundleBuildTab.cs:364
363:       if(m_CopyToStreaming.state)
-->364:           DirectoryCopy(m_UserData.m_OutputPath, m_streamingPath);
365:   }

EditorApplication.Internal_CallDelayFunctions()    C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:200
```

**Comment by alffanclub** [comment]
Hi @NoxMortem  - since you are using the version in package manager (not pulling directly from github) it is expected that this would still be broken as we have not pushed a new update out.  This update (1.7.0) should be coming this week.

-Bill

**Comment by alffanclub** [comment]
no problem.  we aren't getting these releases out as quickly as I'd like :)

**Comment by kakins** [comment]
I'm getting this error even using 1.7.0
