### ISSUE TITLE
How do I set mainAsset?

### ISSUE THREAD

**Issue by mFontoura** [Unity-Technologies/AssetBundles-Browser#70]
I don't see any reference to the mainAsset property. How else could I get a reference to my prefab in the assetbundle?

**Comment by alffanclub** [comment]
Hi @mFontoura, thanks for reaching out.  This is a property of a built bundle that you can't really control.  It is largely unrelated to the loading of your prefabs out of bundles.  The bundle browser is an editor-only tool to help you setup your bundles, but does not assist in the sometimes complex process of loading bundles.  Unity is working on systems to help with that, but for now, to help with loading, you're somewhat stuck going to the docs.  For docs specifically on mainAsset, you can look at: https://docs.unity3d.com/ScriptReference/AssetBundle-mainAsset.html.  For an overall read on working with asset bundles, I'd start here: https://docs.unity3d.com/Manual/AssetBundlesIntro.html
