### ISSUE TITLE
Release Cadence

### ISSUE THREAD

**Issue by StephenHodgson** [Unity-Technologies/AssetBundles-Browser#90]
Hi,

Just wondering what the release cadence was for this package.  Last Release was in March.

**Comment by realJakubSmaga** [comment]
https://forum.unity.com/threads/assetbundle-manager-deprecated.528334/#post-3475104

**Comment by realJakubSmaga** [comment]
As far as I know this has been abandoned and is now being replaced by the new Addressable system.

https://forum.unity.com/threads/assetbundle-manager-deprecated.528334/#post-3475104
https://www.youtube.com/watch?v=t7O1pO8HFRU

**Comment by StephenHodgson** [comment]
The problem is that it's not widely availible yet, correct?

**Comment by StephenHodgson** [comment]
Plus this is still availible in the Package Manager, so technically it's not depreciated until we get an official replacement. But thanks for the heads up.
