### ISSUE TITLE
Can I get a notification of build completion?

### ISSUE THREAD

**Issue by yika-aixi** [Unity-Technologies/AssetBundles-Browser#92]
When AssetBundles completes the packaging, I want to generate AB version information files.How do I know Build Compelte?

**Comment by alffanclub** [comment]
If you look in AssetBundleBuildTab.cs, you can see where we set the on-build callback to refresh our UI... buildInfo.onBuild.  
You can edit that file to have it callback something of your choosing instead (or in addition)

**Comment by yika-aixi** [comment]
OK, all right,Thanks
