### ISSUE TITLE
Missing semi-colon

### ISSUE THREAD

**Issue by elliot-aifi** [Unity-Technologies/AssetBundles-Browser#95]
https://github.com/Unity-Technologies/AssetBundles-Browser/blob/489bdf6d3223723f585d4fff47d869cce8127838/Editor/AssetBundleModel/ABModelAssetInfo.cs#L4

**Comment by realJakubSmaga** [comment]
https://github.com/Unity-Technologies/AssetBundles-Browser/pull/96

**Comment by BrettKercher** [comment]
Thanks for the fix @realJakubSmaga. Should be good now.
